#!/usr/bin/env bash
# Server-lb-01 login commands

# Setting up the SSH agent
eval $("ssh-agent")

# Path to identityFile
ssh-add /alx-system_engineering-devops/0x0B-ssh/school

# Username and IP Address
ssh ubuntu@54.166.133.33
